version: "3.7"

services: 
  node:
    build: 
      context: .
    volumes: 
      - ./:/usr/src/app
    command: sh -c "cd react-app && yarn start"
    networks:
      - container-link
    environment:
      # - VIRTUAL_HOST=localhost # nginx-proxyのホスト設定 ※本番ではlocalhost部分を「example.com,www.example.com」等にする
      - VIRTUAL_HOST=dox.live-on.net 
      # - LETSENCRYPT_HOST=localhost # Let's Encryptのホスト設定 ※本番ではlocalhost部分を「example.com,www.example.com」等にする
      - LETSENCRYPT_HOST=dox.live-on.net
      # - LETSENCRYPT_EMAIL=xxxx@gmail.com # Let's Encryptのメール設定
      - LETSENCRYPT_EMAIL=gaku.jp.301@gmail.com # Let's Encryptのメール設定
      # - LETSENCRYPT_TEST=true # Let's Encryptのテストかどうかのフラグ 本番ではfalseにする (指定しないとテスト扱いになる)
      - LETSENCRYPT_TEST=false
      # - CERT_NAME=default # ローカルで認証局を立てるときに使う ※本番ではLet's Encryptから直接取得するのでコメントアウトする
      # - HTTPS_METHOD=noredirect # リダイレクトを無効にする
    # ports:
    #   - "3000:3000"

networks:
  container-link:
    name: container_network
    external: true
       